version: '3.8'
services:
    db:
        image: postgres:latest
        container_name: whatsapp_postgres
        restart: always
        environment:
            POSTGRES_USER: remcostoeten
            POSTGRES_PASSWORD: mhca6r4g
            POSTGRES_DB: whatsapp
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        name: whatsapp_postgres_data
